# Generated by Django 6.0.4 on 2026-04-20 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filme', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filme',
            old_name='thumn',
            new_name='thumb',
        ),
    ]
